name: Procesar imágenes y subirlas a Azure

on:
  workflow_dispatch:  # Activación manual desde API
  repository_dispatch:  # Evento personalizado desde Logic Apps
    types: [blob_created]  # Nombre del evento

jobs:
  process_images:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar procesamiento de imágenes
        run: |
          node scripts/download.js
          node scripts/resize.js
          node scripts/optimize.js
          node scripts/upload.js
